 create TABLE IF NOT EXISTS USERS (
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    login VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    birthday DATE NOT NULL
);

CREATE TABLE FILMS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(200),
    release_date DATE NOT NULL,
    duration BIGINT NOT NULL,
    mpa_id BIGINT,
    FOREIGN KEY (mpa_id) REFERENCES MPA(id)
);

create TABLE IF NOT EXISTS GENRES (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

create TABLE IF NOT EXISTS MPA (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

create TABLE IF NOT EXISTS FILM_GENRES (
    film_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    PRIMARY KEY (film_id, genre_id),
    FOREIGN KEY (film_id) REFERENCES FILMS(id) ON delete CASCADE,
    FOREIGN KEY (genre_id) REFERENCES GENRES(id) ON delete CASCADE
);

create TABLE IF NOT EXISTS FRIENDSHIP (
    user_id BIGINT NOT NULL,
    friend_id BIGINT NOT NULL,
    status BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (user_id, friend_id),
    FOREIGN KEY (user_id) REFERENCES USERS(id) ON delete CASCADE,
    FOREIGN KEY (friend_id) REFERENCES USERS(id) ON delete CASCADE
);